"""Add products_targeted

Revision ID: 0c1b5716e157
Revises: 3bd540799b91
Create Date: 2026-04-09 22:15:08.202502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c1b5716e157'
down_revision: Union[str, None] = '3bd540799b91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('products_targeted', sa.Text(), nullable=True))
    op.add_column('campaigns', sa.Column('ad_creative_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'ad_creative_url')
    op.drop_column('campaigns', 'products_targeted')
    # ### end Alembic commands ###
