"""User table

Revision ID: 197a0cabb146
Revises:
Create Date: 2025-03-30 21:58:15.666459

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "197a0cabb146"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "test",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("test_1", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_test_email"), "test", ["email"], unique=True)
    op.create_index(op.f("ix_test_id"), "test", ["id"], unique=False)
    op.create_index(op.f("ix_test_name"), "test", ["name"], unique=False)
    op.create_index(op.f("ix_test_test_1"), "test", ["test_1"], unique=True)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column(
            "role",
            sa.Enum("USER", "ADMIN", "MODERATOR", name="userrole"),
            nullable=True,
        ),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("phone_number", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("hashed_password", sa.String(), nullable=True),
        sa.Column("email_verification", sa.String(), nullable=True),
        sa.Column("phone_number_verification", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("phone_number"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_name"), "users", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_name"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_test_test_1"), table_name="test")
    op.drop_index(op.f("ix_test_name"), table_name="test")
    op.drop_index(op.f("ix_test_id"), table_name="test")
    op.drop_index(op.f("ix_test_email"), table_name="test")
    op.drop_table("test")
    # ### end Alembic commands ###
