"""Store and Session table added

Revision ID: 3f1267336646
Revises: 37b8d696689a
Create Date: 2025-05-14 00:16:47.933333

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3f1267336646"
down_revision: Union[str, None] = "37b8d696689a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Store",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("shop", sa.String(), nullable=False),
        sa.Column("state", sa.String(), nullable=True),
        sa.Column("isOnline", sa.Boolean(), nullable=False),
        sa.Column("scope", sa.String(), nullable=True),
        sa.Column("expires", sa.DateTime(), nullable=True),
        sa.Column("accessToken", sa.String(), nullable=False),
        sa.Column("userId", sa.BigInteger(), nullable=True),
        sa.Column("firstName", sa.String(), nullable=True),
        sa.Column("lastName", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("accountOwner", sa.Boolean(), nullable=False),
        sa.Column("locale", sa.String(), nullable=True),
        sa.Column("collaborator", sa.Boolean(), nullable=True),
        sa.Column("emailVerified", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "Store_Session",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("shop", sa.String(), nullable=False),
        sa.Column("saasConnectionStatus", sa.String(), nullable=True),
        sa.Column("verifiedAt", sa.String(), nullable=True),
        sa.Column(
            "createdAt",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("updatedAt", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("Store_Session")
    op.drop_table("Store")
    # ### end Alembic commands ###
