"""user table drop

Revision ID: 45f5d7dfdd8f
Revises: 9822affa706e
Create Date: 2025-05-25 19:41:07.145379

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "45f5d7dfdd8f"
down_revision: Union[str, None] = "9822affa706e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("_prisma_migrations")
    op.drop_index("ix_test_email", table_name="test")
    op.drop_index("ix_test_id", table_name="test")
    op.drop_index("ix_test_name", table_name="test")
    op.drop_index("ix_test_test_1", table_name="test")
    op.drop_table("test")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "test",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("test_1", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="test_pkey"),
    )
    op.create_index("ix_test_test_1", "test", ["test_1"], unique=True)
    op.create_index("ix_test_name", "test", ["name"], unique=False)
    op.create_index("ix_test_id", "test", ["id"], unique=False)
    op.create_index("ix_test_email", "test", ["email"], unique=True)
    op.create_table(
        "_prisma_migrations",
        sa.Column("id", sa.VARCHAR(length=36), autoincrement=False, nullable=False),
        sa.Column(
            "checksum", sa.VARCHAR(length=64), autoincrement=False, nullable=False
        ),
        sa.Column(
            "finished_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "migration_name",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("logs", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "rolled_back_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "started_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "applied_steps_count",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="_prisma_migrations_pkey"),
    )
    # ### end Alembic commands ###
