"""add_ad_accounts_and_campaign_fields

Revision ID: 7695e1d9d2e0
Revises: 013ab27e7827
Create Date: 2026-06-01 14:41:17.204834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7695e1d9d2e0'
down_revision: Union[str, None] = '013ab27e7827'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ad_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ad_accounts_id'), 'ad_accounts', ['id'], unique=False)
    op.add_column('campaigns', sa.Column('external_campaign_id', sa.String(), nullable=True))
    op.add_column('campaigns', sa.Column('ad_account_id', sa.String(), nullable=True))
    op.add_column('campaigns', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'error_message')
    op.drop_column('campaigns', 'ad_account_id')
    op.drop_column('campaigns', 'external_campaign_id')
    op.drop_index(op.f('ix_ad_accounts_id'), table_name='ad_accounts')
    op.drop_table('ad_accounts')
    # ### end Alembic commands ###
